### ISSUE TITLE
can no longer download a published asset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#112] opened 2020-08-01 00:04 UTC
Try downloading e.g. via web ui or via request the single asset on 
https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000027/0.200721.2222/files?location=%2Fsub-RAT123%2F

you would get smth like

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region 'us-east-2' is wrong; expecting 'us-east-1'</Message><Region>us-east-1</Region><RequestId>59B164ED0B5A6C55</RequestId><HostId>GR3DZC8O8s2i5ZND81JD3joTSCSAxTgthXZdWkhlM1zyO536SdTREuEtZEP6LxQhSO/ebWWFh6o=</HostId></Error>%  
```

I would recommend to use this small dataset in a unit/smoke test on dandi-publish or wherever it is pertinent.

**Comment by brianhelba** [comment] 2020-08-01 01:16
This is likely caused by some infrastructure work I've been doing on the deployment. It's not the software itself. I should be able to get it fixed soon.

**Comment by yarikoptic** [comment] 2020-08-03 20:04
Any ETA so we could proceed with testing?

**Comment by mgrauer** [comment] 2020-08-03 20:22
We hope to have this fixed by tomorrow.

**Comment by brianhelba** [comment] 2020-08-05 19:24
I've identified the issue. The fix requires copying the existing data across regions, so it should be complete in 1-2 hours.

I'll post again soon when this is fully resolved.

**Comment by yarikoptic** [comment] 2020-08-05 22:11
Thank you @brianhelba !  how did data migrate across regions? or it just was  "published" originally into the wrong region?

**Comment by brianhelba** [comment] 2020-08-05 23:48
Our bucket for testing publish functionality was created in the wrong region(`us-east-1`, instead of `us-east-2`). Previously, it worked, because the rest of our infrastructure was also in the wrong region, but we recently re-provisioned most of the other infrastructure in the correct region.

In principle, it is possible to configure our infrastructure to talk to buckets in other regions, but it's less configuration burden and closer to the final setup if we just put everything in `us-east-2`.

**Comment by brianhelba** [comment] 2020-08-05 23:48
Also, the copy is still proceeding, about 65% complete.

**Comment by yarikoptic** [comment] 2020-08-06 01:00
Aren't we publishing into the same bucket as used for the drafts, just a different folder?

**Comment by brianhelba** [comment] 2020-08-06 14:50
> Aren't we publishing into the same bucket as used for the drafts, just a different "folder" (prefix/)?

Not yet, but that change is part of the recent infrastructure updates.

**Comment by brianhelba** [comment] 2020-08-06 14:50
This is now resolved.

**Closed by brianhelba** 2020-08-06 14:50 UTC

**Comment by yarikoptic** [comment] 2020-08-06 15:56
confirming - tests of `dandi download` (against main deployment) pass again:

```shell
(git)lena:~/proj/dandi/dandi-cli[enh-download-api]git
$> python -m pytest -v dandi/tests/test_download.py                                                                                           
======================================================================================================= test session starts =======================================================================================================
platform linux -- Python 3.8.5, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /home/yoh/proj/dandi/dandi-cli/venvs/dev3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/yoh/proj/dandi/dandi-cli/.hypothesis/examples')
rootdir: /home/yoh/proj/dandi/dandi-cli, inifile: tox.ini
plugins: xdist-1.31.0, timeout-1.3.3, forked-1.1.3, hypothesis-4.36.2
collected 5 items                                                                                                                                                                                                                 

dandi/tests/test_download.py::test_parse_dandi_url PASSED                                                                                                                                                                   [ 20%]
dandi/tests/test_download.py::test_parse_dandi_url_redirect PASSED                                                                                                                                                          [ 40%]
dandi/tests/test_download.py::test_download_multiple_files PASSED                                                                                                                                                           [ 60%]
dandi/tests/test_download.py::test_download_000027[https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000027/0.200721.2222] PASSED                                                                     [ 80%]
dandi/tests/test_download.py::test_download_000027[https://gui.dandiarchive.org/#/dandiset/5f0640a2ab90ac46c4561e4f] PASSED                                                                                                 [100%]

==================================================================================================== 5 passed in 11.87 seconds ====================================================================================================

$> git describe
0.5.0-73-gc56d948
```
